// Copyright 2018 Zusitools

#ifndef RESOURCE_HPP_
#define RESOURCE_HPP_

#define IDD_HEKTO_CONFIG 100

#define IDC_KLEIN 200
#define IDC_RUECKSTRAHLEND 201
#define IDC_BEIDSEITIG 202
#define IDC_ANKERPUNKT 203
#define IDC_IMMER_OHNE_MAST 204
#define IDC_HAT_UEBERLAENGE 205
#define IDC_BASIS_KM 206
#define IDC_BASIS_HM 207
#define IDC_TEXTUR 208

#endif  // RESOURCE_HPP_
